import type { Site, UnmatchedEmail } from './types';

export const SITES: Site[] = [
  {
    id: 's2',
    address: '38 Birchwood Lane',
    short: '38 Birchwood Ln',
    city: 'Millbrook, NJ',
    lat: 40.762,
    lng: -73.998,
    threads: [
      {
        id: 't2a',
        subject: 'Plumbing rough-in complete',
        sender: 'Maria Santos',
        senderEmail: 'maria@santosplumbing.com',
        initials: 'MS',
        company: 'Santos & Sons Plumbing',
        lastDate: '11h ago',
        messages: [
          {
            id: 'm6',
            from: 'Maria Santos',
            initials: 'MS',
            date: 'Today, 11:15 AM',
            unread: true,
            body: 'Rough-in passed inspection this morning. We can close the walls now. Permit is on file with the township — I\'ll email you a copy this afternoon.',
            attachments: [{ name: 'inspection_cert.pdf', type: 'pdf', size: '95 KB' }],
          },
          {
            id: 'm7',
            from: 'You',
            initials: 'ME',
            date: 'Mar 1, 9:30 AM',
            unread: false,
            body: 'Inspection scheduled for the 3rd — please have the permit on site and accessible.',
          },
          {
            id: 'm8',
            from: 'Maria Santos',
            initials: 'MS',
            date: 'Feb 27, 2:00 PM',
            unread: false,
            body: 'Rough-in is about 80% done. One issue with the supply line to the master bath — we may need to reroute around the load-bearing wall.',
          },
        ],
      },
      {
        id: 't2b',
        subject: 'Fixture selection — owner confirmation',
        sender: 'Maria Santos',
        senderEmail: 'maria@santosplumbing.com',
        initials: 'MS',
        company: 'Santos & Sons Plumbing',
        lastDate: 'Feb 20',
        messages: [
          {
            id: 'm9',
            from: 'You',
            initials: 'ME',
            date: 'Feb 20, 10:00 AM',
            unread: false,
            body: 'Owner confirmed Kohler Bellwether for the master and standard Moen for the guest bath. Please proceed with ordering.',
          },
          {
            id: 'm10',
            from: 'Maria Santos',
            initials: 'MS',
            date: 'Feb 19, 3:30 PM',
            unread: false,
            body: 'Need fixture selections ASAP — lead times are running 3–4 weeks.',
          },
        ],
      },
      {
        id: 't2c',
        subject: 'Demo & rough-in quote',
        sender: 'Maria Santos',
        senderEmail: 'maria@santosplumbing.com',
        initials: 'MS',
        company: 'Santos & Sons Plumbing',
        lastDate: 'Feb 5',
        messages: [
          {
            id: 'm10b',
            from: 'Maria Santos',
            initials: 'MS',
            date: 'Feb 5, 1:00 PM',
            unread: false,
            body: 'Full quote attached. Demo + rough-in for 2 baths and a powder room: $8,400. This includes all supply and drain work to code, but not fixtures.',
            attachments: [{ name: 'Quote_38Birchwood.pdf', type: 'pdf', size: '210 KB' }],
          },
        ],
      },
    ],
  },
  {
    id: 's1',
    address: '145 Oak Street',
    short: '145 Oak St',
    city: 'Millbrook, NJ',
    lat: 40.748,
    lng: -74.021,
    threads: [
      {
        id: 't1a',
        subject: 'Roof inspection — follow-up',
        sender: 'Dave Kowalski',
        senderEmail: 'dave@kowalskiroofing.com',
        initials: 'DK',
        company: 'Kowalski Roofing',
        lastDate: '2h ago',
        messages: [
          {
            id: 'm1',
            from: 'Dave Kowalski',
            initials: 'DK',
            date: 'Today, 2:30 PM',
            unread: true,
            body: 'Completed shingle replacement on the NE section. Flashing around the chimney still needs attention — scheduling that for Friday morning.',
            attachments: [{ name: 'NE_corner_after.jpg', type: 'image', size: '2.4 MB' }],
          },
          {
            id: 'm2',
            from: 'You',
            initials: 'ME',
            date: 'Yesterday, 10:00 AM',
            unread: false,
            body: 'Can you confirm the material spec for the ridge cap? Owner wants to match existing shingles exactly.',
          },
        ],
      },
      {
        id: 't1b',
        subject: 'Invoice #4421 — partial completion',
        sender: 'Dave Kowalski',
        senderEmail: 'dave@kowalskiroofing.com',
        initials: 'DK',
        company: 'Kowalski Roofing',
        lastDate: 'Feb 28',
        messages: [
          {
            id: 'm4',
            from: 'Dave Kowalski',
            initials: 'DK',
            date: 'Feb 28, 4:00 PM',
            unread: false,
            body: 'Attached invoice for the first phase. $3,200 for labor and materials through end of February.',
            attachments: [{ name: 'Invoice_4421.pdf', type: 'pdf', size: '142 KB' }],
          },
        ],
      },
    ],
  },
  {
    id: 's3',
    address: '901 Elmwood Drive',
    short: '901 Elmwood Dr',
    city: 'Cedarcrest, NJ',
    lat: 40.773,
    lng: -74.042,
    threads: [
      {
        id: 't3a',
        subject: 'Electrical panel upgrade — quote review',
        sender: 'Tony Reardon',
        senderEmail: 'tony@reardonelectric.com',
        initials: 'TR',
        company: 'Reardon Electric',
        lastDate: '2d ago',
        messages: [
          {
            id: 'm11',
            from: 'Tony Reardon',
            initials: 'TR',
            date: 'Mar 1, 9:00 AM',
            unread: true,
            body: 'Quote attached. $4,800 for a 200A service upgrade including new panel, breakers, and AFCI protection. Can start March 15 if you give the go-ahead.',
            attachments: [{ name: 'Quote_901Elmwood_Panel.pdf', type: 'pdf', size: '178 KB' }],
          },
          {
            id: 'm12',
            from: 'You',
            initials: 'ME',
            date: 'Feb 28, 11:00 AM',
            unread: false,
            body: 'Owner is requesting a quote for the panel upgrade and any code compliance items.',
          },
        ],
      },
    ],
  },
  {
    id: 's4',
    address: '22 Maple Court',
    short: '22 Maple Ct',
    city: 'Millbrook, NJ',
    lat: 40.741,
    lng: -74.008,
    threads: [
      {
        id: 't4a',
        subject: 'Final walkthrough — all items closed',
        sender: 'Greg Holt',
        senderEmail: 'greg@holtgc.com',
        initials: 'GH',
        company: 'Holt General Contracting',
        lastDate: '1w ago',
        messages: [
          {
            id: 'm13',
            from: 'Greg Holt',
            initials: 'GH',
            date: 'Feb 26, 5:00 PM',
            unread: false,
            body: 'All punch list items resolved. Owner signed the completion form. Certificate of occupancy received — project officially closed.',
            attachments: [
              { name: 'completion_form_signed.pdf', type: 'pdf', size: '520 KB' },
              { name: 'certificate_of_occupancy.pdf', type: 'pdf', size: '180 KB' },
            ],
          },
          {
            id: 'm14',
            from: 'You',
            initials: 'ME',
            date: 'Feb 24, 9:00 AM',
            unread: false,
            body: 'Punch list attached — 6 open items, mostly cosmetic. Can we close by end of week?',
          },
        ],
      },
    ],
  },
  {
    id: 's5',
    address: '477 Cedar Place',
    short: '477 Cedar Pl',
    city: 'Harborview, NJ',
    lat: 40.745,
    lng: -74.048,
    threads: [
      {
        id: 't5a',
        subject: 'Window replacement — phase 1 complete',
        sender: 'Frank Russo',
        senderEmail: 'frank@russowindows.com',
        initials: 'FR',
        company: 'Russo Windows & Doors',
        lastDate: 'Yesterday',
        messages: [
          {
            id: 'm16',
            from: 'Frank Russo',
            initials: 'FR',
            date: 'Yesterday, 4:00 PM',
            unread: true,
            body: 'Phase 1 complete — all 6 south-facing windows installed and sealed. Lead time on the remaining 4 units is 3 weeks.',
            attachments: [
              { name: 'south_windows_complete.jpg', type: 'image', size: '4.2 MB' },
              { name: 'seal_detail.jpg', type: 'image', size: '2.1 MB' },
            ],
          },
          {
            id: 'm17',
            from: 'You',
            initials: 'ME',
            date: 'Mar 4, 11:00 AM',
            unread: false,
            body: 'How are the installs going? Owner asked for an update before the weekend.',
          },
        ],
      },
    ],
  },
  {
    id: 's6',
    address: '67 Riverside Blvd',
    short: '67 Riverside Blvd',
    city: 'Harborview, NJ',
    lat: 40.757,
    lng: -74.035,
    unit: 'Unit 3B',
    threads: [
      {
        id: 't6a',
        subject: 'Bathroom remodel — tile selection',
        sender: 'Maria Santos',
        senderEmail: 'maria@santosplumbing.com',
        initials: 'MS',
        company: 'Santos & Sons Plumbing',
        lastDate: '3d ago',
        messages: [
          {
            id: 'm21',
            from: 'Maria Santos',
            initials: 'MS',
            date: 'Feb 28, 11:00 AM',
            unread: true,
            body: 'Tile samples are in — three options from Daltile. Can we schedule a walkthrough with the tenant for selection? Need to order by the end of next week.',
            attachments: [
              { name: 'daltile_option_A.jpg', type: 'image', size: '1.8 MB' },
              { name: 'daltile_option_B.jpg', type: 'image', size: '1.9 MB' },
              { name: 'daltile_option_C.jpg', type: 'image', size: '2.0 MB' },
            ],
          },
          {
            id: 'm22',
            from: 'You',
            initials: 'ME',
            date: 'Feb 27, 9:00 AM',
            unread: false,
            body: 'Owner wants to keep the bathroom remodel under $6K. What tile options fit that budget?',
          },
        ],
      },
    ],
  },
];

export const UNMATCHED: UnmatchedEmail[] = [
  {
    id: 'u1',
    from: 'Dave Kowalski',
    initials: 'DK',
    subject: 'Re: Material availability',
    date: 'Yesterday, 8:40 AM',
    preview: 'The supplier is backordered on the 30-year architectural shingles…',
    body:
      'Hey — just a heads up that the supplier is backordered on the 30-year architectural shingles in the charcoal blend. They told me the earliest restock is next Wednesday. If the owner is okay with a nearby color, I can swap to Weathered Wood and keep the Friday install slot. Otherwise we should expect about a one week delay. Let me know how you want me to proceed.',
    senderEmail: 'dave@kowalskiroofing.com',
  },
  {
    id: 'u2',
    from: 'Greg Holt',
    initials: 'GH',
    subject: 'Lunch Thursday?',
    date: 'Mar 2, 12:10 PM',
    preview: 'Want to grab lunch and go over the spring schedule? I have a few projects coming up…',
    body:
      'Want to grab lunch Thursday and go over the spring schedule? I have a few projects coming up in Millbrook and Harborview that could use another set of hands, and I figured it would be easier to talk through the timelines in person than over email. I am free after 12:30 if that works for you.',
    senderEmail: 'greg@holtgc.com',
  },
  {
    id: 'u3',
    from: 'Tony Reardon',
    initials: 'TR',
    subject: 'License renewal reminder',
    date: 'Feb 28, 7:45 AM',
    preview: 'Just a reminder my electrical license renewal is coming up in April…',
    body:
      'Just a reminder that my electrical license renewal is coming up in April, so if you need a fresh certificate of insurance or updated license card for any pending permits, I can send those over this week. Nothing urgent on my side — I just wanted to make sure your files stay current.',
    senderEmail: 'tony@reardonelectric.com',
  },
];
